### ISSUE TITLE
Not Detecting Flatpak Steam

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.github.mtkennerly.ludusavi#1]
Even after explicitly pointing to the steam directory, only games installed under ~/.local are detected. I tried giving host permissions but that resulted in the same thing. Is there a workaround for this?

**Comment by mtkennerly** [comment]
* Could you share your configured roots?
* Does this folder exist? `~/.var/app/com.valvesoftware.Steam/.steam/steam` (this is the expected root path)
  * If so, does it contain a `steamapps/common` subfolder with the games?

**Comment by Saroufim** [comment]
Yes to both. I'm running Fedora Silverblue so I thought this could be caused by ~/ linking to /var/home/user instead of /home/user so I wrote the full paths with /var/ included to no avail. It detects 0 games in both cases.

**Comment by mtkennerly** [comment]
Ah, I see. According to [this page](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), host permission does not grant direct access to `/var`. [This post](https://www.reddit.com/r/flatpak/comments/utc6yl/comment/i98vm4i/?utm_source=share&utm_medium=web2x&context=3) suggests that it would be available under `/run/host/var` instead. Could you try enabling host permission and setting the Steam root path to `/run/host/var/home/<USER>/.var/app/com.valvesoftware.Steam/.steam/steam`? Or `/run/host/home/...` might also work.

**Comment by Saroufim** [comment]
I tried with host permissions and host-os permissions. I'm still hitting the same issue. It detects 0 games although it seems to be able to read the path

**Comment by mtkennerly** [comment]
Unfortunately, I'm not sure how to work around that :/ The only other thing I can think to try is making a custom game with the full paths of some specific, known files. That way, you can side-step the root configuration and narrow it down to whether a single, specific path can be recognized. If not, then it's definitely a permissions issue. Something like this, with a few different paths and variations:

> <img width="897" alt="image" src="https://user-images.githubusercontent.com/4934192/188070036-0bc45b26-b68e-48c3-a178-7b497858ef3a.png">

**Comment by Saroufim** [comment]
That didn't work either. By the way, selecting the steam folder using file browsing portal (gtk) shows that the folder it is accessing is /run/user/1000/doc/21da6c8b/Bastion (for Bastion under steamapps/common). Not sure if this is relevant

**Comment by mtkennerly** [comment]
I think that's probably relevant. I wasn't familiar with it, but [I did find this](https://www.reddit.com/r/linux4noobs/comments/u3o45n/comment/i4qigkg/?utm_source=share&utm_medium=web2x&context=3):

> `/run/user/1000/doc` and `/run/user/1000/gvfs` are the mount points of FUSE filesystems that run as the user with UID 1000 (i.e. your regular user). And FUSE by default only allows the user that runs a filesystem to access it. That limitation also applies to root.

**Comment by LeSnake04** [comment]
@Saroufim  can you give acess to /var/home/<USER>/.var/app/com.valvesoftware.Steam/.steam/steam  and re-add the root entry ?

**Comment by Saroufim** [comment]
Your solution worked. Thank you very much.

**Comment by LeSnake04** [comment]
> I think that's probably relevant. I wasn't familiar with it, but [I did find this](https://www.reddit.com/r/linux4noobs/comments/u3o45n/comment/i4qigkg/?utm_source=share&utm_medium=web2x&context=3):
> 
> > `/run/user/1000/doc` and `/run/user/1000/gvfs` are the mount points of FUSE filesystems that run as the user with UID 1000 (i.e. your regular user). And FUSE by default only allows the user that runs a filesystem to access it. That limitation also applies to root.

This is what I ment with my comment in the mainstream issue. This will likely work for backup targets, but not for backup sources

**Comment by LeSnake04** [comment]
> Your solution worked. Thank you very much.

can you remove the host permission and any other extra paths you added trying to fix this aside the one i send you and test it again?

Then I can add it in general

**Comment by Saroufim** [comment]
I had already reset the permissions back to default before trying this

**Comment by LeSnake04** [comment]
Nice, so i will add the path.

**Comment by LeSnake04** [comment]
@mtkennerly  Tip for pushing changes in general: if you make a merge request, the bot will make a test build. that way if something goes wrong behond fixing, you can just close it and open another one and the broken changes dont affect the commit history.

**Comment by mtkennerly** [comment]
Gotcha, and thanks for helping fix this!

**Comment by LeSnake04** [comment]
done #6
