### ISSUE TITLE
Summary shouldn't end with fullstop

### ISSUE THREAD

**Issue by razzeee** [flathub/com.github.mtkennerly.ludusavi#26]

**Comment by mtkennerly** [comment]
Hi! Are there any other guidelines for the phrasing? I'm wondering which of these would be better:

* `Back up your PC video game save data`
* `Tool for backing up your PC video game save data`

**Comment by razzeee** [comment]
Hey, we have some guidelines here, but that might still not help you in that case https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

I would vote for the first one, as it's more to the point and the `Tool` part doesn't add much and might also be obvious?

**Comment by mtkennerly** [comment]
Thanks, that makes sense. I've updated it upstream (https://github.com/mtkennerly/ludusavi/commit/233fa1ce848e0cda60a88bdaf0df2558cebf5504) and opened a PR (https://github.com/flathub/com.github.mtkennerly.ludusavi/pull/27).

**Comment by mtkennerly** [comment]
> <img width="272" alt="image" src="https://github.com/flathub/com.github.mtkennerly.ludusavi/assets/4934192/4c6f3fe4-6190-4762-bc8e-3a3f04f20358">
