### ISSUE TITLE
 Error: The manifest file is invalid.

### ISSUE THREAD

**Issue by 66schoollane** [flathub/com.github.mtkennerly.ludusavi#29]
had this appear after new install of

Error: The manifest file is invalid.
CarX Drift Racing Online.id.steamExtra[8]: invalid value: integer 11124601112420, expected u32 at line
85065 column 9

https://pasteboard.co/UhSY0wGCBvbe.png

never owned this title + did not know it even existed
anyone else had this issue.

**Comment by LeSnake04** [comment]
can recreate. this is very likely not specific to the flatpak version.

I dont have experience with the manifest. 
@mtkennerly can you take a look and if it takes longer to fix maybe temporily pin the manifest to the last working version.

**Comment by mtkennerly** [comment]
Hey, thanks for reporting this, and sorry for the hassle. In the manifest importer, there was a missing validation to ignore IDs that were too large. I've fixed the manifest and [added the validation](https://github.com/mtkennerly/ludusavi-manifest/commit/7249293aa3bbe1e3b0c55785d8778e83176e6e53).

To fix this on your system, just delete `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi/manifest.yaml` and rerun Ludusavi so it can download the latest manifest. I'll also look into adding some protections in Ludusavi itself so it can recover from this kind of error automatically.

**Comment by LeSnake04** [comment]
Looks like the faulty Manifest gets overwritten automatically. Will unpin.
